# Generated by Django 6.0.6 on 2026-07-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctor_available_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('format', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='doctors.doctor')),
            ],
        ),
    ]
