# Generated by Django 6.0.6 on 2026-07-01 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='report_file',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='advice',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='diagnosis',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
