# Generated by Django 6.0.6 on 2026-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
