# Generated by Django 6.0.6 on 2026-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_available_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.JSONField(default=list),
        ),
    ]
