# Generated by Django 6.0.6 on 2026-07-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_available_days_doctor_rating_doctor_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_image',
        ),
    ]
